name: Testing
on: push

jobs:
  test_project:
    runs-on: windows-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install django and run unit tests.
        run: |
          pip install --user django
          python manage.py test
